### ISSUE TITLE
[🐛] Snyk setup action fails inside of ``windows-latest`` github action image trying to execute bash scripts.

### ISSUE THREAD

**Issue by AraHaan** [snyk/cli#1589]
- `node -v`: Using .NET, besides sync install fails within github actions.
- `npm -v`: Using .NET, besides sync install fails within github actions.
- `snyk -v`: Using .NET, besides sync install fails within github actions.
- OS: (e.g. OSX, Linux, Windows, ...) Windows
- Command run: (e.g. `snyk test --all-projects`, `snyk protect`, ...)
Cant run the commands as the action gets skipped to run any due to a failure installing snyk.

### Expected behaviour
Please share _expected_ behaviour.
For it all to work and the project to be evaluated in Snyk. The project uses code that can only be compiled inside of Windows (because it uses the WindowsDesktop SDK on a dll inside of the Sdk I am making).

### Actual behaviour
Please share _problematic_ behaviour you are seeing.
The workflow fails.

### Steps to reproduce
Please share _minimal_ steps needed to reproduce your issue. Ideally
a paired down manifest / project to showcase the problem that can also
be used for testing.

Add this yml to an test .NET project repository (it can target any TFM inside of the .NET 5.0.102 SDK):
```yml
name: Snyk Infrastructure as Code

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '1 * * * *'

jobs:
  snyk:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # we need the submodule to zlib.managed.
          submodules: recursive
      - name: .NET core build
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
      - uses: snyk/actions/setup@master
      - name: Snyk monitor
        run: snyk test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
```

### Debug log
If applicable, please append the `--debug` flag on your command and include the output here **ensuring to remove any sensitive/personal details or tokens**. 
I can do better, I can provide the failing url to the action workflow build: https://github.com/Elskom/Sdk/runs/1755736770?check_suite_focus=true

### Screenshots
N/A Github actions is used and the link should provide all the right details.
