### ISSUE TITLE
rule.startsWith is not a function when running `snyk code test` using more parameters. 

### ISSUE THREAD

**Issue by jegacs** [snyk/cli#4558]
When trying to run add a reason in the .snyk file, I get the following message when running `snyk code test`:

`rule.startsWith is not a function `

The parameters I use in my file are as follows 
```
version: v1.25.0
ignore: {}
patch: {}
exclude:
  global:
    - path-to-file:
        reason: >-
          my reason in string
        created: 2023-04-17T22:30:28.998Z
```
If I don't add more parameters, that is, if I just leave it as following: 
```
version: v1.25.0
ignore: {}
patch: {}
exclude:
  global:
    - path-to-file
```
it just works. 

It seems it is not working when using more parameters other than the path-to-file. 
I'm following this guide: 
https://docs.snyk.io/scan-application-code/snyk-code/cli-for-snyk-code/excluding-directories-and-files-from-the-snyk-code-cli-test

**Comment by KONRADS098** [comment]
When using the snyk cli I encountered the same issue, I ran
`snyk ignore --file-path=path/here --reason='reason here'`

After which the following `.snyk` file was created
```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.25.0
ignore: {}
patch: {}
exclude:
  global:
    - path/here:
        reason: >-
          reason here
        created: 2023-06-17T14:23:11.163Z

```

In the pipeline, I then received an unexpected exit code with the following message
`rule.startsWith is not a function`
